version: "3.9" 
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Data
      - MONGO_INITDB_ROOT_PASSWORD=hurmardu
    volumes:
      - scraped_data:/data/db
      
  scraper:
    image: python:3.10-slim
    volumes:
      - ./scraper:home/scraper


volumes:
  scraped_data: {}
